name: CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.402' # SDK Version to use.
      - run: dotnet --list-runtimes && dotnet --list-sdks
      - run: git submodule update --init
      - run: dotnet build
